
export const FETCH_CHARACTERS = 'FETCH_CHARACTERS';
export const FETCH_ALL_CHARACTERS = 'FETCH_ALL_CHARACTERS';
export const FETCH_ALL_CHARACTERS_DONE = 'FETCH_ALL_CHARACTERS_DONE';
export const FETCH_CHARACTERS_DONE = 'FETCH_CHARACTERS_DONE';
export const FETCH_CHARACTERS_ERROR = 'FETCH_CHARACTERS_ERROR';
export const FETCH_FILTERED_CHARACTERS = 'FETCH_FILTERED_CHARACTERS';
