export const ADD_CHARACTERS_HISTORY = 'ADD_CHARACTERS_HISTORY';
export const ADD_LOCATIONS_HISTORY = 'ADD_LOCATIONS_HISTORY';
export const ADD_EPISODES_HISTORY = 'ADD_EPISODES_HISTORY';
export const CLEAN_HISTORY = 'CLEAN_HISTORY';