export const FETCH_LOCATIONS = 'FETCH_LOCATIONS';
export const FETCH_LOCATIONS_DONE = 'FETCH_LOCATIONS_DONE';
export const FETCH_LOCATIONS_CACHE = 'FETCH_LOCATIONS_CACHE';
export const FETCH_LOCATIONS_ERROR = 'FETCH_LOCATIONS_ERROR';
export const FETCH_FILTERED_LOCATIONS = 'FETCH_FILTERED_LOCATIONS';