export const FETCH_EPISODES = 'FETCH_EPISODES';
export const FETCH_EPISODES_DONE = 'FETCH_EPISODES_DONE';
export const FETCH_EPISODES_CACHE = 'FETCH_EPISODES_CACHE';
export const FETCH_EPISODES_ERROR = 'FETCH_EPISODES_ERROR';
export const FETCH_FILTERED_EPISODES = 'FETCH_FILTERED_EPISODES';